# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20161203_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='net_1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='net_2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='net_3',
        ),
        migrations.RemoveField(
            model_name='item',
            name='offer_1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='offer_2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='offer_3',
        ),
        migrations.AddField(
            model_name='item',
            name='offer_285',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name=b'Oferta 28+5'),
        ),
        migrations.AddField(
            model_name='item',
            name='offer_294',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name=b'Oferta 29+4'),
        ),
        migrations.AddField(
            model_name='item',
            name='offer_303',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name=b'Oferta 30+3'),
        ),
    ]
